# Generated by Django 5.1.3 on 2024-11-15 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
